# Generated by Django 4.2.16 on 2024-11-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='link_foto',
            field=models.CharField(blank=True),
        ),
    ]
