# Generated by Django 4.2.16 on 2024-11-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0002_perfiles_link_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
