# Generated by Django 4.2.16 on 2024-11-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0003_perfiles_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='is_staff',
        ),
    ]
