# Generated by Django 4.2.16 on 2024-11-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0004_remove_perfiles_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='numero_telefonico',
            field=models.CharField(blank=True, unique=True),
        ),
    ]
