# Generated by Django 4.2.16 on 2024-11-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0005_alter_perfiles_numero_telefonico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='contraseña',
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='numero_telefonico',
            field=models.CharField(unique=True),
        ),
    ]
