# Generated by Django 4.2.16 on 2024-11-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0006_remove_perfiles_contraseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
