# Generated by Django 4.2.16 on 2024-11-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0007_perfiles_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='perfiles',
            name='contraseña',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
