# Generated by Django 4.2.16 on 2024-11-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0009_alter_perfiles_numero_telefonico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='numero_telefonico',
            field=models.CharField(unique=True),
        ),
    ]
