# Generated by Django 4.2.16 on 2024-11-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0010_perfiles_is_staff_alter_perfiles_numero_telefonico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
