# Generated by Django 4.2.16 on 2024-11-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Perfiles', '0011_alter_perfiles_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='perfiles_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='perfiles_user_permissions', to='auth.permission'),
        ),
    ]
