# Generated by Django 4.2.16 on 2024-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_direccionesenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionesenvio',
            name='pais',
            field=models.CharField(default='VENEZUELA'),
        ),
    ]
