# Generated by Django 4.2.16 on 2024-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_alter_direccionesenvio_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='direcciones',
            field=models.ManyToManyField(to='Clientes.direccionesenvio'),
        ),
    ]
