# Generated by Django 4.2.16 on 2024-11-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_clientes_direcciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='auth_provider',
            field=models.CharField(default='google', max_length=50),
        ),
    ]
