# Generated by Django 4.2.16 on 2024-11-12 10:40

import backend.utils.get_expiration_date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_clientes_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('expiration_date', models.DateTimeField(default=backend.utils.get_expiration_date.get_expiration_date)),
            ],
        ),
    ]
