# Generated by Django 4.2.16 on 2024-11-12 11:11

import backend.utils.generate_verification_token
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_clientes_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(default=backend.utils.generate_verification_token.generate_verification_token, max_length=10),
        ),
    ]
