# Generated by Django 4.2.16 on 2024-11-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_alter_verificationtoken_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationtoken',
            options={'verbose_name': 'VerificationToken', 'verbose_name_plural': 'VerificationTokens'},
        ),
    ]
