# Generated by Django 4.2.16 on 2024-11-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_rename_direccion_1_direccionesenvio_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion_preferida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_preferidos', to='Clientes.direccionesenvio'),
        ),
    ]
