# Generated by Django 4.2.16 on 2024-11-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0012_alter_clientes_direccion_preferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion_preferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_preferidos', to='Clientes.direccionesenvio'),
        ),
    ]
