# Generated by Django 4.2.16 on 2025-01-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0015_alter_clientes_direcciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionesenvio',
            name='ciudad',
            field=models.CharField(default='CARACAS'),
        ),
    ]
