# Generated by Django 5.1.3 on 2025-03-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0016_alter_direccionesenvio_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionesenvio',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direccionesenvio',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
