# Generated by Django 4.2.16 on 2024-11-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='password',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='user_permissions',
        ),
    ]
