# Generated by Django 4.2.16 on 2024-11-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0002_alter_perfiles_numero_telefonico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='stripeCustomerId',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
