# Generated by Django 4.2.16 on 2024-11-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0003_perfiles_stripecustomerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='stripeCustomerId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
