# Generated by Django 4.2.16 on 2024-11-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0005_alter_perfiles_stripecustomerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
