# Generated by Django 4.2.16 on 2024-11-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0007_verificationtokens_perfiles_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtokens',
            name='token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
