# Generated by Django 4.2.16 on 2024-11-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0008_alter_verificationtokens_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='verification_token',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Perfiles.verificationtokens'),
        ),
    ]
