# Generated by Django 4.2.16 on 2024-11-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0010_alter_perfiles_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='verification_token',
        ),
        migrations.DeleteModel(
            name='VerificationTokens',
        ),
    ]
