# Generated by Django 4.2.16 on 2024-11-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0011_remove_perfiles_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='verification_token',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
