# Generated by Django 4.2.16 on 2024-11-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0013_alter_perfiles_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='verification_token',
        ),
    ]
