# Generated by Django 4.2.16 on 2024-11-12 12:39

import backend.utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0014_remove_perfiles_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='rol',
            field=models.CharField(choices=[('administrador', 'ADMIN'), ('empleado', 'EMPLEADO'), ('cliente', 'CLIENTE')], default=backend.utils.constants.RolEnum['EMPLEADO']),
        ),
    ]
