# Generated by Django 4.2.16 on 2024-11-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0015_alter_perfiles_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='nombre_completo',
            field=models.CharField(),
        ),
    ]
