# Generated by Django 4.2.16 on 2024-11-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0016_alter_perfiles_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='numero_telefonico',
            field=models.CharField(blank=True, null=True),
        ),
    ]
