# Generated by Django 4.2.16 on 2024-12-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0017_alter_perfiles_numero_telefonico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='cedula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
