# Generated by Django 4.2.16 on 2024-12-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0018_perfiles_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='cedula',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
