# Generated by Django 4.2.16 on 2024-11-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
