# Generated by Django 4.2.16 on 2024-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
