# Generated by Django 4.2.16 on 2024-11-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0012_alter_pedidos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numero_de_orden',
            field=models.IntegerField(unique=True),
        ),
    ]
