# Generated by Django 4.2.16 on 2024-11-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0013_alter_pedidos_numero_de_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='descripcion_pedido',
            field=models.JSONField(default=list),
        ),
    ]
