# Generated by Django 4.2.16 on 2024-11-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0015_remove_pedidos_descripcion_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descripcionespedido',
            options={'verbose_name': 'Descripción de pedido', 'verbose_name_plural': 'Descripciones de pedidos'},
        ),
    ]
