# Generated by Django 4.2.16 on 2024-11-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0025_alter_presentaciones_calorias_and_more'),
        ('Ventas', '0016_alter_descripcionespedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionespedido',
            name='presentacion_asociada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='descripciones_pedido', to='Productos.presentaciones'),
        ),
    ]
