# Generated by Django 4.2.16 on 2024-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0018_alter_pedidos_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
