# Generated by Django 4.2.16 on 2024-11-13 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0013_alter_clientes_direccion_preferida'),
        ('Ventas', '0020_alter_descripcionespedido_pedido_asociado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='direccion',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='direccion_entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='Clientes.direccionesenvio'),
        ),
    ]
