# Generated by Django 4.2.16 on 2024-11-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0023_alter_pedidos_monto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcionespedido',
            name='producto_asociado',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
