# Generated by Django 4.2.16 on 2024-11-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0024_remove_descripcionespedido_producto_asociado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='pedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='Ventas.pedidos'),
        ),
    ]
