# Generated by Django 4.2.16 on 2024-12-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0025_alter_ventas_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='precio_delivery',
            field=models.IntegerField(blank=True, choices=[(1, 'CENTRO_HISTORICO'), (2, 'SABANA_GRANDE'), (3, 'ALTAMIRA'), (4, 'PETARE')], default=1, null=True),
        ),
    ]
