# Generated by Django 4.2.16 on 2024-12-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0026_pedidos_precio_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='prueba',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
