# Generated by Django 4.2.16 on 2025-01-01 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0028_remove_pedidos_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision_factura', models.DateTimeField()),
                ('domicilio_fiscal', models.CharField(blank=True, default='Santa Rosa de Lima')),
                ('numero_telefonico_empresa', models.CharField(blank=True, default='+58 4242955147')),
                ('rif_empresa', models.CharField(blank=True, default='J-310651032')),
                ('correo_electronico_empresa', models.EmailField(blank=True, default='kapatortas@gmail.com', max_length=254)),
                ('venta_asociada', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='Ventas.ventas')),
            ],
        ),
    ]
