# Generated by Django 5.1.3 on 2025-01-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0029_facturas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturas',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
