# Generated by Django 4.2.16 on 2025-01-02 08:51

import backend.utils.get_current_time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0029_facturas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturas',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fecha_emision_factura',
            field=models.DateTimeField(default=backend.utils.get_current_time.get_current_time),
        ),
    ]
