# Generated by Django 5.1.4 on 2025-01-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0030_alter_facturas_options'),
        ('Ventas', '0030_alter_facturas_options_and_more'),
    ]

    operations = [
    ]
