# Generated by Django 4.2.16 on 2025-01-02 23:21

import backend.utils.get_current_time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0030_alter_facturas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(default=backend.utils.get_current_time.get_current_time),
        ),
    ]
