# Generated by Django 5.1.3 on 2025-01-03 17:45

import backend.utils.get_current_time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0031_merge_20250102_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(default=backend.utils.get_current_time.get_current_time),
        ),
    ]
