# Generated by Django 5.1.4 on 2025-01-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0031_alter_ventas_fecha'),
        ('Ventas', '0032_alter_ventas_fecha'),
    ]

    operations = [
    ]
