# Generated by Django 5.1.4 on 2025-01-04 19:27

import backend.utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0033_merge_0031_alter_ventas_fecha_0032_alter_ventas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('recibido', 'RECIBIDO'), ('en_proceso', 'EN_PROCESO'), ('cancelado', 'CANCELADO'), ('finalizado', 'FINALIZADO')], default=backend.utils.constants.EstadoEnum['RECIBIDO']),
        ),
    ]
