# Generated by Django 5.1.4 on 2025-01-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0033_merge_0031_alter_ventas_fecha_0032_alter_ventas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='iva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
