# Generated by Django 5.1.4 on 2025-01-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0034_pedidos_iva_pedidos_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='iva',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nota',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
