# Generated by Django 5.1.4 on 2025-01-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0035_alter_pedidos_iva_alter_pedidos_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='iva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
