# Generated by Django 5.1.3 on 2025-01-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0034_alter_pedidos_estado'),
        ('Ventas', '0036_alter_pedidos_iva'),
    ]

    operations = [
    ]
