# Generated by Django 5.1.4 on 2025-01-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0037_merge_20250104_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionespedido',
            name='sabor',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
