# Generated by Django 5.1.4 on 2025-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0038_descripcionespedido_sabor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcionespedido',
            name='sabor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
