# Generated by Django 5.1.3 on 2025-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0039_alter_descripcionespedido_sabor_alter_pedidos_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
