# Generated by Django 5.1.4 on 2025-01-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0040_facturas_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='precio_delivery',
            field=models.IntegerField(blank=True, choices=[(0, 'PICK_UP'), (1, 'CENTRO_HISTORICO'), (2, 'SABANA_GRANDE'), (3, 'ALTAMIRA'), (4, 'PETARE')], default=3, null=True),
        ),
    ]
