# Generated by Django 4.2.16 on 2024-11-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_resenia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resenia',
        ),
    ]
