# Generated by Django 4.2.16 on 2024-11-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_clientes_options_remove_clientes_groups_and_more'),
        ('Productos', '0006_delete_resenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('cliente_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenias', to='Clientes.clientes')),
            ],
        ),
    ]
