# Generated by Django 4.2.16 on 2024-11-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_clientes_options_remove_clientes_groups_and_more'),
        ('Productos', '0007_resenia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resenia',
            new_name='Resenias',
        ),
    ]
