# Generated by Django 4.2.16 on 2024-11-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_rename_resenia_resenias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resenias',
        ),
    ]
