# Generated by Django 4.2.16 on 2024-11-08 16:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_resenias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resenias',
            options={'verbose_name': 'Resenia', 'verbose_name_plural': 'Resenias'},
        ),
        migrations.AddField(
            model_name='productos',
            name='imagenes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
