# Generated by Django 4.2.16 on 2024-11-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_clientes_options_remove_clientes_groups_and_more'),
        ('Productos', '0011_alter_resenias_options_productos_imagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('cliente_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Clientes.clientes')),
                ('producto_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Productos.productos')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.DeleteModel(
            name='Resenias',
        ),
    ]
