# Generated by Django 4.2.16 on 2024-11-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_descripcionproducto_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='DescripcionProducto',
        ),
    ]
