# Generated by Django 4.2.16 on 2024-11-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0014_alter_productos_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristicas', models.TextField()),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.descripcionproducto'),
        ),
    ]
