# Generated by Django 4.2.16 on 2024-11-11 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0016_productos_calorias_alter_productos_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='proporciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pequeño', 'PEQUEÑO'), ('mediano', 'MEDIANO'), ('grande', 'GRANDE')], max_length=10), blank=True, default=list, size=None),
        ),
    ]
