# Generated by Django 5.1.3 on 2024-11-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0017_productos_proporciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='calorias',
        ),
    ]
