# Generated by Django 5.1.3 on 2024-11-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0018_remove_productos_calorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='proporciones',
        ),
    ]
