# Generated by Django 4.2.16 on 2024-11-12 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0020_productos_calorias_productos_proporciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
