# Generated by Django 4.2.16 on 2024-11-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0021_alter_reviews_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='proporciones',
        ),
    ]
