# Generated by Django 4.2.16 on 2024-11-12 23:25

import backend.utils.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0022_remove_productos_proporciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='stock',
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('postre', 'POSTRE'), ('extra', 'EXTRA')], default=backend.utils.constants.CategoriaProductoEnum['POSTRE']),
        ),
        migrations.CreateModel(
            name='Presentaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.TextField()),
                ('proporcion', models.CharField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField()),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producto_asociado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='presentaciones', to='Productos.productos')),
            ],
        ),
    ]
