# Generated by Django 4.2.16 on 2024-11-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0024_alter_presentaciones_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentaciones',
            name='calorias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='presentaciones',
            name='proporcion',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentaciones',
            name='ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
