# Generated by Django 5.1.4 on 2025-01-04 20:52

import backend.utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0030_remove_presentaciones_calorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('especial', 'ESPECIAL'), ('postre', 'POSTRE'), ('extra', 'EXTRA')], default=backend.utils.constants.CategoriaProductoEnum['POSTRE']),
        ),
    ]
